### ISSUE TITLE
Makefile could be improved

### ISSUE THREAD

**Issue by FOMX** [RAYMUNDOOOO/flappy-bin-chicken#6]
Currently, the makefile is a bit light and requires user attention to build. There are also some minor issues. 

- [Line 2](https://github.com/RAYMUNDOOOO/flappy-bin-chicken/blob/39319fb06addb0675c244ee7bc8c9416bdcc2320/makefile#L2C5-L2C5) The LIBS variable should probably be LDLIBS. see [here](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html#index-LDLIBS).
- [Lines 6-12](https://github.com/RAYMUNDOOOO/flappy-bin-chicken/blob/39319fb06addb0675c244ee7bc8c9416bdcc2320/makefile#L6-L12C6) contain tabs when i think they maybe should be spaces. Tabs are for recipes, spaces are for makefile syntax. see [here](https://www.gnu.org/software/make/manual/html_node/Recipe-Syntax.html) and [here](https://www.gnu.org/software/make/manual/html_node/Simple-Makefile.html#index-recipe).
- [Lines 15-17](https://github.com/FOMX/flappy-bin-chicken/blob/39319fb06addb0675c244ee7bc8c9416bdcc2320/makefile#L15-L17) I think raylib.h should be included as part of the built raylib library that's kept with the LIBS/LDLIBS. So either build the raylib separately as part of the whole project build process (build raylib then flappy-bin-chicken) or include a path to the pre-built raylib libs in the makefile. 

To do this in the makefile a decision needs to be made about the paths involved. 
1. Raylib could be maintained within this library as a submodule that is built. This path would be absolute. 
    - This means this project will have to maintain a copy of raylib sourcecode (either manual copy, additional git remote, or god forbid git submodules)
    - This simplifies builds as it guarantees the exact raylib required and other devs don't need to isntall raylib.
    - The templater tool [game-premake](https://github.com/raylib-extras/game-premake) does it this way and so do all the projects based on it. see [here](https://github.com/TheEnbyWitch/LunarViewer), [here](https://github.com/iatsrangalov20/DockCoders), [here](https://github.com/Denisbaic/RedBrixCppTest), [here](https://github.com/LATL9/RCT)
    - This bloats the project a bit imo as it's including the entire engine in the source. This is a consequence of the language and lack of package manager.
    - RAYLIB_PATH = `./raylib-master` or RAYLIB_PATH = `../raylib-master`
    - This would probably be best done with 3 make files. 1 in the parent project, 1 in raylib, and 1 in the game directory. 
2. Raylib could be the folder above the parent. 
    - This is what the examples do as they are stored inside the main raylib project - `C:\raylib\raylib\examples`
    - this is a bit naff imo, but it simplifies the config as all platforms have the same raylib path. 
    - RAYLIB_PATH = `../..`
    - additionally a RAYLIB_VERSION variable should be used to check the version being used. 
3. The folder could be based on a default installation path that's hardcoded for each OS. This works well for windows. Linux i'm not sure what the path would be as the user can copy the source code anywhere. For the most part the installed files are located at `/usr/local/lib`. 
    - Windows: RAYLIB_PATH = `C:/raylib/raylib`
    - Linux: RAYLIB_PATH = ?
    - additionally a RAYLIB_VERSION variable should be used to check the version being used.

**Comment by RAYMUNDOOOO** [comment]
Woah thanks for all the feedback, I'll try and implement these changes based on your feedback ❤️

**Comment by FOMX** [comment]
haha no problem. I was playing around with it before and realised a decision needs to be made about the project architecture to get the makefile working properly. The end goal being able to use github ci.

additionally a build dir and a clean command are nice
- two good options for the build dir are `_build` and `build` with `_build` appearing more popular with the raylib projects out there
- the clean command could then just rm -f $(BUILD_DIR)/* or whatever 
    - usage: `make clean`

**Comment by FOMX** [comment]
Sorry for the edits to the main comments. I fixed some typos and added some additional info.

**Comment by FOMX** [comment]
I made 3 branches trying out some of the the different methods for linking to raylib.

I actually think best method is the git submodule method despite being infamously tricky
- as raylib is an external dependency that could never change (for this project) there shouldn't be any merge conflicts
- `--recurse-submodules` is needed for some operations like `git switch`/ `git checkout`. Without this flag the submodules won't be "switched". Again, I don't think this will be an issue if the project never updates raylib.
- `git clone --recursive` without `--recursive`, the raylib submodule won't be cloned. This is important for CI. 

1 Con is that if you use submodules, you won't be able to easily edit the raylib project, although i'm not sure why you would need to do that. You'd have to fork the project and create your own branch.  

Other than that, I think it's a good way to do it as it keeps the project clean. I'm not sure why other projects don't do it this way.


I won't PR it as it's a good thing to do yourself. 

[raylib submodule](https://github.com/FOMX/flappy-bin-chicken/tree/makefile_with_raylib_submodule)
[raylib copy](https://github.com/FOMX/flappy-bin-chicken/tree/makefile_with_raylib_copy)
[no raylib but fixed paths](https://github.com/FOMX/flappy-bin-chicken/tree/makefile_fixed_install)

**Comment by FOMX** [comment]
lol tab and space closed the issue... thanks github.

**Comment by RAYMUNDOOOO** [comment]
Need to add to the `makefile` to see if raylib is already in the user's environment variables, because if it already is then we don't need to pull the raylib submodule.

**Comment by RAYMUNDOOOO** [comment]
Makefile needs further refactoring to account for changes in #11. Will start working on this now.

**Comment by RAYMUNDOOOO** [comment]
Done! Makefile has now been refactored to have one in the root directory that will build raylib using the makefile in `raylib/` and then continue building the game after configuring flags for the user's operating system. Files have also been further moved around in the directory structure.
